### ISSUE TITLE
Code is available

### ISSUE THREAD

**Issue by shi27feng** [Yangzhangcst/Transformer-in-Computer-Vision#1]
Hi @Yangzhangcst 
Thank you for this repo.
The code for paper "STAR: Sparse Transformer-based Action Recognition" is available at the link:
https://github.com/imj2185/STAR

**Comment by Yangzhangcst** [comment]
> Hi @Yangzhangcst
> Thank you for this repo.
> The code for paper "STAR: Sparse Transformer-based Action Recognition" is available at the link:
> https://github.com/imj2185/STAR

Thanks for your help. We have updated this project.
