### ISSUE TITLE
Please add our paper to your list

### ISSUE THREAD

**Issue by jacobdang** [Yangzhangcst/Transformer-in-Computer-Vision#2]
Our paper titled "Bilateral-ViT for Robust Fovea Localization" has been accepted to ISBI 2022 conference and a preprint is available at this link: https://arxiv.org/abs/2110.09860

I would appreciate it a lot if you can add our paper to your list. Thanks!

**Comment by Yangzhangcst** [comment]
> Our paper titled "Bilateral-ViT for Robust Fovea Localization" has been accepted to ISBI 2022 conference and a preprint is available at this link: https://arxiv.org/abs/2110.09860
> 
> I would appreciate it a lot if you can add our paper to your list. Thanks!

Thanks for your help. We have updated this project.
