### ISSUE TITLE
Hello. CVPR 2023 paper.

### ISSUE THREAD

**Issue by wjun0830** [Yangzhangcst/Transformer-in-Computer-Vision#5]
Hello! Great work!

I would like to introduce the CVPR2023 paper called QD-DETR (Query-Dependent Detection Transformer) which belongs to Video category.
Title : Query-Dependent Video Representation for Moment Retrieval and Highlight Detection

```
arxiv link : https://arxiv.org/abs/2303.13874
Github link : https://github.com/wjun0830/QD-DETR
cvpr openaccess : https://openaccess.thecvf.com/content/CVPR2023/papers/Moon_Query-Dependent_Video_Representation_for_Moment_Retrieval_and_Highlight_Detection_CVPR_2023_paper.pdf
```

Thank you.

**Comment by Yangzhangcst** [comment]
Thanks for your help, we have updated this project.


> 你好！做得好！
> 
> 我想介绍一下CVPR2023论文QD-DETR（Query-DependentDetectionTransformer），属于视频类别。 标题：用于时刻检索和亮点检测的查询相关视频表示
> 
> ```
> arxiv link : https://arxiv.org/abs/2303.13874
> Github link : https://github.com/wjun0830/QD-DETR
> cvpr openaccess : https://openaccess.thecvf.com/content/CVPR2023/papers/Moon_Query-Dependent_Video_Representation_for_Moment_Retrieval_and_Highlight_Detection_CVPR_2023_paper.pdf
> ```
> 
> 谢谢。

**Comment by Yangzhangcst** [comment]
> Hello! Great work!
> 
> I would like to introduce the CVPR2023 paper called QD-DETR (Query-Dependent Detection Transformer) which belongs to Video category. Title : Query-Dependent Video Representation for Moment Retrieval and Highlight Detection
> 
> ```
> arxiv link : https://arxiv.org/abs/2303.13874
> Github link : https://github.com/wjun0830/QD-DETR
> cvpr openaccess : https://openaccess.thecvf.com/content/CVPR2023/papers/Moon_Query-Dependent_Video_Representation_for_Moment_Retrieval_and_Highlight_Detection_CVPR_2023_paper.pdf
> ```
> 
> Thank you.

Thanks for your help, we have updated this project.
